# -- coding: utf-8 --
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: produtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprodutos.proto\"\x1c\n\x0eProdutoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"A\n\x12InfoBasicaResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\"@\n\x0f\x45stoqueResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x01\x12\x12\n\nquantidade\x18\x03 \x01(\x05\x32\x43\n\x08\x43\x61talogo\x12\x37\n\rGetInfoBasica\x12\x0f.ProdutoRequest\x1a\x13.InfoBasicaResponse\"\x00\x32?\n\nInventario\x12\x31\n\nGetEstoque\x12\x0f.ProdutoRequest\x1a\x10.EstoqueResponse\"\x00\x42\x18Z\x16projeto-catalogo/protob\x06proto3')



_PRODUTOREQUEST = DESCRIPTOR.message_types_by_name['ProdutoRequest']
_INFOBASICARESPONSE = DESCRIPTOR.message_types_by_name['InfoBasicaResponse']
_ESTOQUERESPONSE = DESCRIPTOR.message_types_by_name['EstoqueResponse']
ProdutoRequest = _reflection.GeneratedProtocolMessageType('ProdutoRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUTOREQUEST,
  '_module_' : 'produtos_pb2'
  # @@protoc_insertion_point(class_scope:ProdutoRequest)
  })
_sym_db.RegisterMessage(ProdutoRequest)

InfoBasicaResponse = _reflection.GeneratedProtocolMessageType('InfoBasicaResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFOBASICARESPONSE,
  '_module_' : 'produtos_pb2'
  # @@protoc_insertion_point(class_scope:InfoBasicaResponse)
  })
_sym_db.RegisterMessage(InfoBasicaResponse)

EstoqueResponse = _reflection.GeneratedProtocolMessageType('EstoqueResponse', (_message.Message,), {
  'DESCRIPTOR' : _ESTOQUERESPONSE,
  '_module_' : 'produtos_pb2'
  # @@protoc_insertion_point(class_scope:EstoqueResponse)
  })
_sym_db.RegisterMessage(EstoqueResponse)

_CATALOGO = DESCRIPTOR.services_by_name['Catalogo']
_INVENTARIO = DESCRIPTOR.services_by_name['Inventario']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026projeto-catalogo/proto'
  _PRODUTOREQUEST._serialized_start=18
  _PRODUTOREQUEST._serialized_end=46
  _INFOBASICARESPONSE._serialized_start=48
  _INFOBASICARESPONSE._serialized_end=113
  _ESTOQUERESPONSE._serialized_start=115
  _ESTOQUERESPONSE._serialized_end=179
  _CATALOGO._serialized_start=181
  _CATALOGO._serialized_end=248
  _INVENTARIO._serialized_start=250
  _INVENTARIO._serialized_end=313
# @@protoc_insertion_point(module_scope)