# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calcular_media_pb2 as calcular__media__pb2


class CalculadorDeMediaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalcularMedia = channel.stream_unary(
                '/calcular_media.CalculadorDeMedia/CalcularMedia',
                request_serializer=calcular__media__pb2.NumeroRequest.SerializeToString,
                response_deserializer=calcular__media__pb2.MediaResponse.FromString,
                )


class CalculadorDeMediaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalcularMedia(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadorDeMediaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalcularMedia': grpc.stream_unary_rpc_method_handler(
                    servicer.CalcularMedia,
                    request_deserializer=calcular__media__pb2.NumeroRequest.FromString,
                    response_serializer=calcular__media__pb2.MediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calcular_media.CalculadorDeMedia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculadorDeMedia(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalcularMedia(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/calcular_media.CalculadorDeMedia/CalcularMedia',
            calcular__media__pb2.NumeroRequest.SerializeToString,
            calcular__media__pb2.MediaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
