# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calcular_media.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61lcular_media.proto\x12\x0e\x63\x61lcular_media\"\x1e\n\rNumeroRequest\x12\r\n\x05valor\x18\x01 \x01(\x05\"\x1e\n\rMediaResponse\x12\r\n\x05valor\x18\x01 \x01(\x01\x32\x66\n\x11\x43\x61lculadorDeMedia\x12Q\n\rCalcularMedia\x12\x1d.calcular_media.NumeroRequest\x1a\x1d.calcular_media.MediaResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calcular_media_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NUMEROREQUEST']._serialized_start=40
  _globals['_NUMEROREQUEST']._serialized_end=70
  _globals['_MEDIARESPONSE']._serialized_start=72
  _globals['_MEDIARESPONSE']._serialized_end=102
  _globals['_CALCULADORDEMEDIA']._serialized_start=104
  _globals['_CALCULADORDEMEDIA']._serialized_end=206
# @@protoc_insertion_point(module_scope)
