# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: downloader.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ownloader.proto\x12\ndownloader\",\n\x11RequisicaoArquivo\x12\x17\n\x0fnome_do_arquivo\x18\x01 \x01(\t\" \n\x05\x43hunk\x12\x17\n\x0fpedaco_de_dados\x18\x01 \x01(\x0c\x32S\n\nDownloader\x12\x45\n\rBaixarArquivo\x12\x1d.downloader.RequisicaoArquivo\x1a\x11.downloader.Chunk\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'downloader_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUISICAOARQUIVO']._serialized_start=32
  _globals['_REQUISICAOARQUIVO']._serialized_end=76
  _globals['_CHUNK']._serialized_start=78
  _globals['_CHUNK']._serialized_end=110
  _globals['_DOWNLOADER']._serialized_start=112
  _globals['_DOWNLOADER']._serialized_end=195
# @@protoc_insertion_point(module_scope)
