# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import downloader_pb2 as downloader__pb2


class DownloaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BaixarArquivo = channel.unary_stream(
                '/downloader.Downloader/BaixarArquivo',
                request_serializer=downloader__pb2.RequisicaoArquivo.SerializeToString,
                response_deserializer=downloader__pb2.Chunk.FromString,
                )


class DownloaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BaixarArquivo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BaixarArquivo': grpc.unary_stream_rpc_method_handler(
                    servicer.BaixarArquivo,
                    request_deserializer=downloader__pb2.RequisicaoArquivo.FromString,
                    response_serializer=downloader__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'downloader.Downloader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Downloader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BaixarArquivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/downloader.Downloader/BaixarArquivo',
            downloader__pb2.RequisicaoArquivo.SerializeToString,
            downloader__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
