// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: app-principal/produtos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProdutoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProdutoRequest) Reset() {
	*x = ProdutoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_principal_produtos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProdutoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdutoRequest) ProtoMessage() {}

func (x *ProdutoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_principal_produtos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdutoRequest.ProtoReflect.Descriptor instead.
func (*ProdutoRequest) Descriptor() ([]byte, []int) {
	return file_app_principal_produtos_proto_rawDescGZIP(), []int{0}
}

func (x *ProdutoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Mensagem de resposta do serviço Catalogo (A)
type InfoBasicaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome      string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao string `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
}

func (x *InfoBasicaResponse) Reset() {
	*x = InfoBasicaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_principal_produtos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoBasicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoBasicaResponse) ProtoMessage() {}

func (x *InfoBasicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_principal_produtos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoBasicaResponse.ProtoReflect.Descriptor instead.
func (*InfoBasicaResponse) Descriptor() ([]byte, []int) {
	return file_app_principal_produtos_proto_rawDescGZIP(), []int{1}
}

func (x *InfoBasicaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InfoBasicaResponse) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *InfoBasicaResponse) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

// Mensagem de resposta do serviço Inventario (B)
type EstoqueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Preco      float64 `protobuf:"fixed64,2,opt,name=preco,proto3" json:"preco,omitempty"`
	Quantidade int32   `protobuf:"varint,3,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
}

func (x *EstoqueResponse) Reset() {
	*x = EstoqueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_principal_produtos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstoqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstoqueResponse) ProtoMessage() {}

func (x *EstoqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_principal_produtos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstoqueResponse.ProtoReflect.Descriptor instead.
func (*EstoqueResponse) Descriptor() ([]byte, []int) {
	return file_app_principal_produtos_proto_rawDescGZIP(), []int{2}
}

func (x *EstoqueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EstoqueResponse) GetPreco() float64 {
	if x != nil {
		return x.Preco
	}
	return 0
}

func (x *EstoqueResponse) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

var File_app_principal_produtos_proto protoreflect.FileDescriptor

var file_app_principal_produtos_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x70, 0x2d, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20,
	0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x56, 0x0a, 0x12, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x22, 0x57, 0x0a, 0x0f, 0x45, 0x73, 0x74, 0x6f,
	0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x65, 0x63, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x65, 0x63,
	0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64,
	0x65, 0x32, 0x43, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x37, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x61, 0x12, 0x0f,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x3f, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x61, 0x72, 0x69, 0x6f, 0x12, 0x31, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x6f, 0x71,
	0x75, 0x65, 0x12, 0x0f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x45, 0x73, 0x74, 0x6f, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x74, 0x6f, 0x73, 0x2d, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_principal_produtos_proto_rawDescOnce sync.Once
	file_app_principal_produtos_proto_rawDescData = file_app_principal_produtos_proto_rawDesc
)

func file_app_principal_produtos_proto_rawDescGZIP() []byte {
	file_app_principal_produtos_proto_rawDescOnce.Do(func() {
		file_app_principal_produtos_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_principal_produtos_proto_rawDescData)
	})
	return file_app_principal_produtos_proto_rawDescData
}

var file_app_principal_produtos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_principal_produtos_proto_goTypes = []interface{}{
	(*ProdutoRequest)(nil),     // 0: ProdutoRequest
	(*InfoBasicaResponse)(nil), // 1: InfoBasicaResponse
	(*EstoqueResponse)(nil),    // 2: EstoqueResponse
}
var file_app_principal_produtos_proto_depIdxs = []int32{
	0, // 0: Catalogo.GetInfoBasica:input_type -> ProdutoRequest
	0, // 1: Inventario.GetEstoque:input_type -> ProdutoRequest
	1, // 2: Catalogo.GetInfoBasica:output_type -> InfoBasicaResponse
	2, // 3: Inventario.GetEstoque:output_type -> EstoqueResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_principal_produtos_proto_init() }
func file_app_principal_produtos_proto_init() {
	if File_app_principal_produtos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_principal_produtos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProdutoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_principal_produtos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoBasicaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_principal_produtos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstoqueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_principal_produtos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_app_principal_produtos_proto_goTypes,
		DependencyIndexes: file_app_principal_produtos_proto_depIdxs,
		MessageInfos:      file_app_principal_produtos_proto_msgTypes,
	}.Build()
	File_app_principal_produtos_proto = out.File
	file_app_principal_produtos_proto_rawDesc = nil
	file_app_principal_produtos_proto_goTypes = nil
	file_app_principal_produtos_proto_depIdxs = nil
}
