# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculadora_pb2 as calculadora__pb2


class CalculadoraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Somar = channel.unary_unary(
                '/calculadora.Calculadora/Somar',
                request_serializer=calculadora__pb2.RequisicaoSoma.SerializeToString,
                response_deserializer=calculadora__pb2.RespostaSoma.FromString,
                )


class CalculadoraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Somar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Somar': grpc.unary_unary_rpc_method_handler(
                    servicer.Somar,
                    request_deserializer=calculadora__pb2.RequisicaoSoma.FromString,
                    response_serializer=calculadora__pb2.RespostaSoma.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculadora(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Somar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculadora.Calculadora/Somar',
            calculadora__pb2.RequisicaoSoma.SerializeToString,
            calculadora__pb2.RespostaSoma.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
